BirthdayAT/Models/ErrorViewModel.cs
namespace BirthdayAT.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BirthdayAT/Models/Friend.cs
using Microsoft.EntityFrameworkCore;

namespace BirthdayAT.Models
{
    public class Friend
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Birthday { get; set; }
    }
}

BirthdayAT/Models/ModelContext.cs
using Microsoft.EntityFrameworkCore;

namespace BirthdayAT.Models
{
    public class ModelContext : DbContext
    {
        public DbSet<Friend> Friends { get; set; }
        public ModelContext(DbContextOptions<ModelContext> options) : base(options)
        {

        }
    }
}

BirthdayAT/Controllers/FriendController.cs
using BirthdayAT.Models;
using Microsoft.AspNetCore.Mvc;

namespace BirthdayAT.Controllers
{
    public class FriendController : Controller
    {

        private readonly ModelContext _db;

        public FriendController(
            ModelContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        // GET: Friend/Delete/5
        public ActionResult Delete(string LastName)
        {
            var friends = _db.Friends;
            var frientToDelete = friends.Where(f => f.LastName == LastName).First();
            friends.Remove(frientToDelete);
            _db.SaveChanges();
           
            return View("~/Views/Home/Index.cshtml", friends.ToList());
        }

        // GET: Friend/Edit/5
        public ActionResult Edit(Friend friend)
        {
            return View((Friend)friend);
        }

        // POST: Friend/EditFriend/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFriend(int Id, IFormCollection friendData)
        {
            var friends = _db.Friends;
            Console.WriteLine(friendData);
            var birthday = Convert.ToDateTime(friendData["Birthday"]);
            var firstName = (String)friendData["FirstName"];
            var lastName = (String)friendData["LastName"];

            var frientToUpdate = friends.Where(f => f.Id == Id).First();
            frientToUpdate.FirstName = firstName;
            frientToUpdate.LastName = lastName;
            frientToUpdate.Birthday = birthday;
            _db.SaveChanges();

            return View("~/Views/Home/Index.cshtml", friends.ToList());
        }

        // POST: Friend/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection friendData)
        {
            var friends = _db.Friends;
            Console.WriteLine(friendData);
            var birthday = Convert.ToDateTime(friendData["Birthday"]);
            var firstName = (String)friendData["FirstName"];
            var lastName = (String)friendData["LastName"];

            Friend friend = new();
            friend.FirstName = firstName;
            friend.LastName = lastName;
            friend.Birthday = birthday;
            _db.Add(friend);
            _db.SaveChanges();

            return View("~/Views/Home/Index.cshtml", friends.ToList());
        }

    }
}

BirthdayAT/Controllers/HomeController.cs
using BirthdayAT.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BirthdayAT.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ModelContext _db;

        public HomeController(
            ILogger<HomeController> logger,
            ModelContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index()
        {
            var friends = _db.Friends.OrderByDescending(f => f.Birthday).ToList(); 
            return View(friends);
        }

        public IActionResult Edit()
        {
            var friends = _db.Friends.OrderByDescending(f => f.Birthday).ToList();
            return View(friends);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BirthdayAT/Views/Friend/Edit.cshtml
@model Friend

<h1>Adicionar Amigo:</h1>
<form method="post" action="/Friend/EditFriend/@Model.Id">
    @Html.AntiForgeryToken()
    <label>Nome</label>
    <input type="text" name="FirstName" value="@Model.FirstName"/>
    <label>Sobrenome</label>
    <input type="text" name="LastName" value="@Model.LastName" />
    <label>Aniversário</label>
    <input type="date" name="Birthday" value="@Model.Birthday" />

    <input type="submit" value="Enviar" />
</form>

BirthdayAT/Views/Home/Edit.cshtml
@model List<BirthdayAT.Models.Friend>

<h1>Adicionar Amigo:</h1>
<form method="post" action="/Friend/Create">
    @Html.AntiForgeryToken()
    <label>Nome</label>
    <input type="text" name="FirstName" />
    <label>Sobrenome</label>
    <input type="text" name="LastName" />
    <label>Aniversário</label>
    <input type="date" name="Birthday" />

    <input type="submit" value="Enviar" />
</form>


<h1>Editar Amigos:</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Sobrenome</td>
            <td>Aniversário</td>
            <td>Editar</td>
            <td>Excluir</td>
        </tr>
    </thead>
@{
    foreach (var friend in Model)
    {
        <tr>
            <td>
                @friend.FirstName
            </td>
            <td>
                @friend.LastName
            </td>
            <td>
                @friend.Birthday.ToString()
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", "Friend", friend )
            </td>
            <td>
                @Html.ActionLink("Excluir", "Delete", "Friend", new { LastName = friend.LastName })
            </td>
        </tr>
    }
}
</table>

BirthdayAT/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var today = DateTime.Now.Date;
}

@model List<BirthdayAT.Models.Friend>

<h1>Amigos de aniversário hoje:</h1>
<ul>
    @{
        foreach (var friend in Model)
        {
            if (friend.Birthday.Date == today) 
            {
                <li>
                    @friend.FirstName
                </li>
            }
            
        }
    }
</ul>

<h1>Aniversários:</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Aniversário</td>
        </tr>
    </thead>
    @{
        foreach (var friend in Model)
        {
            <tr>
                <td>
                    @friend.FirstName
                </td>
                <td>
                    @friend.Birthday.ToString()
                </td>
            </tr>
        }
    }
</table>

<button type="button" onclick="location.href='@Url.Action("Edit","Home")'">Gerenciar Aniversários</button>

BirthdayAT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BirthdayAT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BirthdayAT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BirthdayAT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BirthdayAT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>